spring:
  application:
    name: aws
  data:
    mongodb:
      database: aws
      host: ${ENV_DB_HOST:localhost}
      port: ${ENV_DB_PORT:27017}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  security:
    jwtSecret: fCeDw+hIGGCwSVFo0Y883e3iko8s4huUSqDswc8mXk6xFyTnof0ihw==
    jwtExpiration: 86400000

aws:
  access-key: ${AWS_ACCESS_KEY:test}
  secret-key: ${AWS_SECRET_KEY:test}
  region: ${AWS_REGION:us-east-1}
  endpoint: ${AWS_ENDPOINT:http://localhost:4566}
  bucket: ${AWS_S3_BUCKET:test-bucket}
