spring:
  application:
    name: aws

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  security:
    jwtSecret: fCeDw+hIGGCwSVFo0Y883e3iko8s4huUSqDswc8mXk6xFyTnof0ihw==
    jwtExpiration: 86400000

aws:
  access-key: ${AWS_ACCESS_KEY:}
  secret-key: ${AWS_SECRET_KEY:}
  region: ${AWS_REGION:ap-southeast-1}
  endpoint: ${AWS_ENDPOINT:https://${aws.bucket}.s3.${aws.region}.amazonaws.com}
  bucket: ${AWS_S3_BUCKET:moment-sharing}
